### ISSUE TITLE
Crash when using

### ISSUE THREAD

**Issue by bmulholland** [warleysr/ankipa#4]
I hit Cmd+W, hit Save, and the following error occurs:

Debug info:
Anki 2.1.54 (b6a7760c) Python 3.9.7 Qt 6.3.1 PyQt 6.3.1
Platform: Mac 13.1
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-01-13 09:25:05
Add-ons possibly involved: ⁨AnkiPA - Pronunciation Assessment for Anki⁩

Caught exception:
Traceback (most recent call last):
  File "aqt.taskman", line 122, in _on_closures_pending
  File "aqt.taskman", line 71, in <lambda>
  File "aqt.sound", line 623, in and_then
  File "aqt.sound", line 552, in stop
  File "aqt.sound", line 765, in after_record
  File "/Users/bmulholland/Library/Application Support/Anki2/addons21/86363097/ankipa.py", line 72, in after_record
    from .pronunciation import pron_assess
  File "/Users/bmulholland/Library/Application Support/Anki2/addons21/86363097/pronunciation.py", line 3, in <module>
    from ankipa import AnkiPA
ModuleNotFoundError: No module named 'ankipa'

**Comment by warleysr** [comment]
I changed the way of importing the module in d93f615 as well. Could you try again? I tested in Windows 11 and Ubuntu. I don't have a Mac to test on.

**Comment by bmulholland** [comment]
That fixed the crash, thank you!

I do get another issue now, which I'll file separately.
